name: read-secrets
on: [push, workflow_dispatch]

jobs:

  # An example that uses Key Vault to login to a container registry
  docker-login:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - id: get-secrets
      uses: azure/get-keyvault-secrets@v1
      with:
        keyvault: "[[ YOUR_KEYVAULT_NAME ]]"
        secrets: 'acr-username, acr-password'
    - name: login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: yourcontainerregistry.azurecr.io
        username: ${{ steps.get-secrets.outputs.acr-username }}
        password: ${{ steps.get-secrets.outputs.acr-password }}

  # An example that uses Key Vault to download a blob using a storage account key
  read-secrets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - id: get-secrets
      uses: azure/get-keyvault-secrets@v1
      with:
        keyvault: "[[ YOUR_KEYVAULT_NAME ]]"
        secrets: 'storage-key'
    - name: download file with storage account key
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob download \
            --account-name yourstorageaccountname \
            --account-key ${{ steps.get-secrets.outputs.storage-key }} \
            --container yourcontainer \
            --name uploadedfile.txt \
            --file downloadedfile.txt
    - name: write out file contents
      run: |
        cat downloadedfile.txt
